src/components/query/PropertyQueryEditor.tsx
Adding missing undefined check
fixes #54
=> adding undefined check

src/components/browser/BrowseHierarchy.tsx, src/sitewiseCache.ts
adding parent drill up
This is an 'mvp' feature, and should eventually be replaced by a trie view.
=> adding parent drill up

pkg/sitewise/client/client.go
=> add user agent

src/common/Card.tsx, src/components/browser/BrowseHierarchy.tsx, src/components/browser/BrowseModels.tsx, src/components/browser/hierarchy/AssetHierarchyList.tsx, src/components/browser/hierarchy/AssetList.tsx, src/components/browser/hierarchy/AssetListItem.tsx
this approach seems better to me...
and
=> use card component

.drone.cue
Add .drone.cue for Drone configuration.
**NB:** The required extension isn't yet installed on our main Drone server.
=> Drone: Add .drone.cue

src/plugin.json
Fixes #65,  This will update the link under:
=> add link to issues page

README.md, src/README.md
these are some quick edits to avoid "TODO" and make the dev build links more clear they are for development!
=> Docs: minor improvements to readme

package.json
=> bump dev version to 1.2.5

package.json, src/common/Card.tsx, src/components/browser/AssetBrowser.tsx, src/components/browser/BrowseHierarchy.tsx, src/components/browser/BrowseModels.tsx, src/components/browser/hierarchy/AssetHierarchyList.tsx, src/components/browser/hierarchy/AssetList.tsx, yarn.lock
this fixes: https://github.com/grafana/support-escalations/issues/1421
=> fix: use theme2 and update deps

CHANGELOG.md, package.json
also pulls in the latest released CHANGELOG from 1.2.5
=> bump dev version to 1.2.6

CHANGELOG.md, package.json
this updates the changelog & bumps the dev version for the v1.2.6 release
=> Update CHANGELOG.md for 1.2.6

src/README.md
=> README: Fix provisioning example

.github/CODEOWNERS, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/issue_commands.json, .github/pull_request_template.md, .github/release.yml, .github/workflows/code-coverage.yml, .github/workflows/detect-breaking-changes.yml, .github/workflows/issue-commands.yml, README.md, cspell.config.json, go.mod, go.sum, package.json, yarn.lock
Fixes [#156](https://github.com/grafana/iot-sitewise-datasource/issues/156)
=> Modify templates and add workflows for AWS Plugins squad

.github/CODEOWNERS
=> update CODEOWNERS to reflect correct team name

CHANGELOG.md, cspell.config.json, package.json
=> Release 1.10.2

package.json, yarn.lock
relates to https://github.com/grafana/oss-plugin-partnerships/issues/223
=> Upgrade grafana-aws-sdk

.github/workflows/issue-commands.yml
Properly fix workflow - same as https://github.com/grafana/grafana-iot-twinmaker-app/pull/222
=> Use Github App credentials for issue commands workflow

.github/workflows/issue-commands.yml
no need to assign PRs in our project board
=> Don't run issue_commands flow on PRs

package.json, yarn.lock
This adds underscore v1.12.1 to the resolutions in package.json. 
This adds debug v2.6.9 to the resolutions in package.json.
Fixes https://github.com/grafana/oss-plugin-partnerships/issues/475
Fixes https://github.com/grafana/oss-plugin-partnerships/issues/473
=> Upgrade underscore, debug dependencies

CHANGELOG.md, jest-setup.js, package.json, src/components/AggregatePicker.tsx, src/components/ConfigEditor.test.tsx, src/components/ConfigEditor.tsx, src/components/query/ListAssetsQueryEditor.tsx, src/components/query/PropertyQueryEditor.tsx, src/components/query/QualityAndOrderRow.tsx, src/components/query/QueryEditor.test.tsx, src/components/query/QueryEditor.tsx, src/components/query/QueryOptions.tsx, src/types.ts, yarn.lock
Migrating Config Editor to the new design system form components, as well as the Query Editor to use EditorField components from grafana/experimental.
The new components are under a Grafana feature flag `awsDatasourcesNewFormStyling`.
**What was done**
Replace the editor inline fields for the grafana/ui Field components if the feature flag is enabled
**What was done**
- Use new vertical form fields instead of inline
- separated out the query options for Expand Time Range, Format, Quality, Time into a collapse. 
I did this because they were squeezed after other fields, like Property, and weren't that visible either. But if there's a strong reason for these being accessible right after the fields, I can put them back. …
=> Query and Config editors: Migrate to new form styling under feature toggle 

CHANGELOG.md, package.json
=> Release 1.15.0

CHANGELOG.md, package.json
=> Release 1.16.1

src/components/query/PropertyQueryEditor.tsx, src/components/query/QueryEditor.test.tsx
**Which issue(s) this PR fixes**: https://github.com/grafana/iot-sitewise-datasource/issues/273
=> fix: clear selected property when assets are removed

pkg/framer/fields/fields.go, pkg/framer/fields/util.go, pkg/framer/list_asset_properties.go, pkg/framer/property_interpolated.go, pkg/framer/property_value_batch.go, pkg/framer/property_value_history.go, pkg/framer/property_value_history_batch.go, pkg/framer/util.go, pkg/models/asset.go, pkg/models/property.go, pkg/models/query.go, pkg/server/handlers.go, pkg/server/server.go, pkg/server/test/list_asset_properties_test.go, pkg/sitewise/api/list_asset_properties.go, pkg/sitewise/datasource.go, pkg/testdata/data.go, pkg/testdata/list-asset-properties-A.golden.jsonc, pkg/testdata/list-asset-properties.json, pkg/util/resources.go, src/components/query/ListAssetsQueryEditor.tsx, src/components/query/PropertyQueryEditor.tsx, src/sitewiseCache.ts, src/types.ts
**What this PR does / why we need it**: This change enables the visualization of component properties. Instead of utilizing the list of asset properties contained within DescribeAsset, ListAssetProperties is utilized. See https://github.com/grafana/iot-sitewise-datasource/issues/269.
=> feat: support composite model properties

CHANGELOG.md, package.json
Add some missing items to changelog, change release to be a minor, si…nce we're adding new functionality with composite model support
=> Prepare release for 1.17.0

CHANGELOG.md, cspell.config.json, package.json
- Fix fetching asset properties in (#302)[https://github.com/grafana/iot-sitewise-datasource/pull/302]
- Feature: L4E struct support in (#300)[https://github.com/grafana/iot-sitewise-datasource/pull/300]
- Response processing: Add struct data type handling in (#297)[https://github.com/grafana/iot-sitewise-datasource/pull/297]
- Query Editor: Improve menu placement for dropdowns in (#292)[https://github.com/grafana/iot-sitewise-datasource/pull/292]
- Add keywords in (#291)[https://github.com/grafana/iot-sitewise-datasource/pull/291]
- E2E: Add happy path playwright query tests in (#290)[https://github.com/grafana/iot-sitewise-datasource/pull/290]
- Query Editor: Stop running queries on every change in (#274)[https://github.com/grafana/iot-sitewise-datasource/pull/274]
=> Prepare 1.18.0

CHANGELOG.md, package.json
prepare the release for 1.20.0
=> prepare release 1.20.0

CHANGELOG.md, package.json
=> prepare release v1.22.0

CHANGELOG.md, cspell.config.json, package.json
**What this PR does / why we need it**: Release changes since July
**Which issue(s) this PR fixes**: 
All changes in release:
- fix: add check for nil for property value (#352)
- Fix golangci-lint errors (#353)
- fix: migrate asset id on the frontend in the query editor (#350)
- Remove "ANY" as a query quality option (#347)
- Chore: Rename datasource file (#344)
- Add precommit hook (#338)
- Remove unused fields from Get property value query editor (#343)
- Remove ANY option for interpolated property quality (#342)
Fixes #354
=> Release 1.24.0

CHANGELOG.md, package.json
**What this PR does / why we need it**: Release change for batch calls causing 500 errors
All changes in release:
- Fix: batch entries up to the limit specified in the API #355
Fixes #356
=> release 1.25.0

CHANGELOG.md, package.json
=> prepare release 1.25.1

README.md, package.json, src/components/ConfigEditor.tsx, src/components/query/ClientCacheRow.tsx, src/components/query/ListAssetsQueryEditor.tsx, src/components/query/ListTimeSeriesQueryEditor.tsx, src/components/query/PropertyQueryEditor.tsx, src/components/query/QualityAndOrderRow.tsx, src/components/query/QueryEditor.tsx, src/components/query/QueryOptions.tsx, src/plugin.json, yarn.lock
=> Migrate to plugin-ui from grafana/experimental

src/SitewiseDataSource.ts, src/components/browser/BrowseHierarchy.tsx, src/components/query/ListAssetsQueryEditor.tsx, src/sitewiseCache.ts
Fixes https://github.com/grafana/iot-sitewise-datasource/issues/423
=> Add variable interpolation for model id

src/common/getSelectionInfo.ts, src/components/query/visual-query-builder/PropertyQueryEditor.tsx, src/components/query/visual-query-builder/QualityAndOrderRow.tsx, src/components/query/visual-query-builder/VisualQueryBuilder.tsx, src/queryResponseTypes.ts, src/types.ts
Small improvement to remove dead code from the client side.
=> chore remove dead code

pkg/server/handlers_test.go, pkg/server/test/list_associated_assets_test.go, pkg/sitewise/api/list_associated_assets.go, pkg/testdata/const.go, pkg/testdata/list-associated-assets-multiple-A.golden.jsonc, pkg/testdata/list-associated-assets-multiple.json
Adds support for handling multiple asset ids when using a "List associated assets" query.
Fixes #403
I created Power Plant model and added a Motor model as part of its hierarchy. The below is an example of a "List associated assets" query with multiple asset ids.
The changes also handle the cases where an asset has multiple parents as shown in the diagram [here](https://docs.aws.amazon.com/iot-sitewise/latest/userguide/asset-hierarchies.html).
Some notes on the changes:
- `pkg/server/handlers_test.go` added `assetIds` to the request since the updated code in `pkg/sitewise/api/list_associated_assets.go` loops through all of the asset ids to handle multiple assets, without this …
=> Add support for listing associated assets for multiple assets

src/components/query/visual-query-builder/PropertyQueryEditor.tsx, src/components/query/visual-query-builder/QualityAndOrderRow.tsx
This change modernizes PropertyQueryEditor and QualityAndOrderRow by refactoring to function components. Some additional minor improvements were done, yet the change is mostly restructuring from class to function components.
=> chore: refactor additional class components

.github/pr-commands.json, .github/workflows/pr-commands.yml, cspell.config.json
Adds a workflow for pull requests to add a `pr/external` label for external contributions and also add it to our team board
=> Chore: add label to external contributions

tests/configEditor.spec.ts
=> e2e: use @grafana/plugin-e2e api to check config success

.github/workflows/issue-commands.yml, .github/workflows/pr-commands.yml, .github/zizmor.yml
I've already added the secrets to vault
=> add vault tokens and zizmor config

CHANGELOG.md, package.json
=> Prepare 2.2.1 release

.github/workflows/publish.yaml, CHANGELOG.md, package.json
Test to see if the action is fixed so we can release. See more https://raintank-corp.slack.com/archives/C01C4K8DETW/p1754298419751359?thread_ts=1740049098.295989&cid=C01C4K8DETW
2.3.1 and 2.3.2 weren't released so setting this one as 2.3.1 again
=> Rerelease 2.3.1
