- src/components/browser/BrowseHierarchy.tsx
- src/components/browser/hierarchy/AssetHierarchyList.tsx
- src/components/browser/hierarchy/AssetList.tsx
Lists parents as cards rather than a dropdown.  Still a little funky, but good enough?
> parent as card

- src/components/browser/AssetBrowser.tsx
- src/components/browser/BrowseHierarchy.tsx
- src/components/query/PropertyQueryEditor.tsx
- src/components/query/QueryEditor.tsx
- src/sitewiseCache.ts
- fixed issue where changing region does not cascade to children
- reset the query asset/property ID to `undefined` when switching regions
- fixed sizing issue when asset is undefined in HierachyBrowser
> allow for graceful switching of regions within query editor

- go.mod
- go.sum
This includes two auth fixes:
1. UTC consistenty in timeouts https://github.com/grafana/grafana-aws-sdk/pull/2
2. (not relevant) better migrations for old settings https://github.com/grafana/grafana-aws-sdk/pull/3
> update auth sdk

- src/components/browser/hierarchy/AssetHierarchyList.tsx
When multiple hierarchies are present, the AssetHierarchyList elements have large margins between each. This makes it appear as the other hierarchies are not being loaded.
Changing height to auto with a 10px top margin.
> fixing styling on AssetHierarchyList containers

- package.json
- src/plugin.json
- yarn.lock
Please test and verify that your normal path for authenticating the plugin works. Please also verify that the query editor looks alright and it's possible to get data from the backend.
What has changed in the aws-sdk? 
* made grafana/ui and grafana/data dev dependencies
* remove dependency to grafana/runtime. instead reading config from grafanaBootData
* made it possible to opt out on ConnectionConfig legend header and endpoint field (a requirement for sigv4)
* add unit tests
The API has not changed, so there should be no need to make changes to the ConfigEditor.tsx. 
Please release the plugin when this pr has been merged to master, and then let Jon know the new version number.
> use latest grafana/aws-sdk

- pkg/sitewise/auth.go
- pkg/sitewise/auth_test.go
see https://github.com/grafana/iot-sitewise-datasource/pull/101#discussion_r677028062
> better edge auth test

- package.json
- pkg/framer/property_value_history.go
- pkg/framer/util.go
- pkg/models/property.go
- pkg/models/query.go
- pkg/resource/caching_resource_provider.go
- pkg/resource/caching_resource_provider_test.go
- pkg/resource/query_resouce_provider.go
- pkg/resource/sitewise.go
- pkg/sitewise/api/property_aggregate.go
- pkg/sitewise/api/property_history.go
- pkg/sitewise/api/property_value.go
- pkg/sitewise/api/test_data_test.go
- pkg/sitewise/api/util.go
- pkg/testdata/property-history-values-with-alias.json
- src/DataSource.ts
- src/components/query/PropertyQueryEditor.tsx
- src/components/query/QueryEditor.tsx
- src/types.ts
- yarn.lock
Fixes #98
This adds `propertyAlias` to the UI and query model for anything that accept it
Still totally untested since I don't know any real alias values to try :)
> Allow query by property alias

- CHANGELOG.md
- package.json
- src/DataSource.ts
- src/sitewiseCache.ts
Adds query variables to asset and property dropdowns:
Related to fixes for #113
> Add support for variables in query editor

- pkg/server/last-observation.go
- pkg/server/server.go
- pkg/sitewise/api/property_aggregate.go
- src/components/query/PropertyQueryEditor.tsx
- src/types.ts
Fixes #139.
This requires the changes in https://github.com/grafana/grafana/pull/59444
The is the same query in Grafana 9.3.0 (without the changes in https://github.com/grafana/grafana/pull/59444)
> Query for last values outside time range

- go.mod
- go.sum
This upgrades grafana-aws-sdk which contains the updated opt-in regions list 
Part of [https://github.com/grafana/grafana-aws-sdk/pull/66](https://github.com/grafana/grafana-aws-sdk/pull/66)
> Update aws-sdk-go for the opt-in region list

- src/components/query/PropertyQueryEditor.tsx
- src/components/query/QueryEditor.tsx
Closes https://github.com/grafana/iot-sitewise-datasource/issues/170 and does the same for `query type` InlineField
> Set property alias and query type to have interactive tooltips

- src/DataSource.ts
- src/module.ts
- src/variables.ts
This replaces the deprecated `setVariableQueryEditor` with `CustomVariableSupport` modeled after what is used in the Athena datasource.
Fixes #154
I made an attempt to updated the deprecated setVariableQueryEditor. If I'm not mistaken in the build, I think it's working! I modeled it off of what is done in Athena.
Any suggestions are very welcome!
Here's the video of the change:
https://github.com/grafana/iot-sitewise-datasource/assets/4163034/40debff9-1617-499e-8622-3e56e79f142b
Now the regex filters by the name of the values for the regex.
> Replace deprecated setVariableQueryEditor with CustomVariableSupport

- go.mod
- pkg/server/handlers.go
- pkg/server/test/property_value_aggregate_test.go
- pkg/server/test/property_value_history_test.go
- pkg/sitewise/api/property_history.go
- pkg/sitewise/client/client.go
This PR fixes an issue where queries with an expression do not show all data points.
Fixes #160, #182, #195
To be able to test this, you can use the Sitewise assets in the external dev account. Note, the demo assets live for 7 days before being deleted. If you see an error indicating that the resources can not be found, you can go to the Sitewise dashboard in the AWS console and create demo assets (there is a button to do so in the top right of the dashboard page)
The main issue here is that expression queries do not call the datasource's query method. Instead [if an expression query is present](https://github.com/grafana/grafana/blob/8235f774aa1afb49254861f3d6d3ea691baedde3/publi …
> Fix handle expression queries with more than 250 data points

- pkg/sitewise/client/client.go
Fixes an issue where some data points are duplicated.
Fixes #200
Here's a sample python script that can fetch the expected number of data points for a property aggregate query using boto3. Make sure you have boto3 installed. You may need to update the `assetId`, `propertyId`, `startDate`, and `endDate` if the sample data in external dev has expired and you recreate the demo data. Your Sitewise data source should be configured for the external dev account. You can use the Stat panel and set the calculation value to "Count" to compare the number of data points from the script below (just make sure the time range matches the python script).
```py
import boto3
from datetime import …
```
> Fix: Property aggregate queries returning duplicated data

- pkg/server/handlers.go
- pkg/server/test/property_value_aggregate_test.go
- pkg/server/test/property_value_history_test.go
Fixes an issue where queries with expression return partial data only. In a previous PR queries with expressions were set to execute completely on the backend before returning data to the frontend. This was done by setting the maximum number of datapoints and pages to fetch to `math.Inf(1)`. This worked locally, but when the Sitewise data source was built, `math.Inf(1)` ended up being a negative number. This caused the backend to only return the first page of data because the function that fetches the data from Sitewise would check if the current number of datapoints/pages is less than the maximum number of datapoints/pages it should fetch https://github.com/grafana/iot-sitewise-datasource/blob/c70aadea564390be9388ba2d8eaa11c273229fa3/pkg/sitewise/cl …
> Fix: Query with expression only returns partial data

- CHANGELOG.md
- package.json
- yarn.lock
While testing sandboxing, I got errors related to use of grafanaBootData in Sitewise version of aws-sdk. The package has previously been updated to use config instead of grafanaBootData, so this is just to update the dependency to contain the new code.
> Update grafana/aws-sdk-react dependency and prepare v1.10.3

- CHANGELOG.md
- package.json
- pkg/resource/query_resouce_provider.go
- pkg/server/test/property_value_aggregate_test.go
- pkg/server/test/property_value_test.go
- pkg/testdata/property-history-values-boolean-disassociated-empty-response.json
- pkg/testdata/property-history-values-boolean-disassociated.json
- pkg/testdata/property-value-disassociated.json
- pkg/util/ids.go
When implementing disassociated data streams, I set the entryID to be equal to the propertyAlias. Normally for associated streams it is set to assetID. This isn't possible for disassociated streams since they don't have an asset connected to them. 
However, I didn't account for property aliases that are longer than 64 characters. 
One possible solution is to hash the property aliases. As far as I can see, they don't need to be in human readable format, since entryId is used on our BE to:
1. send along with queries to distinguish them and
2. access the results of those queries, be they success or errors, and append them to our frames. 
The names of the frames/fields don't come from entryIDs but from the property aliases from the query, which are …
> Disassociated streams: Hash entryId to fix bug with property aliases longer than 64 characters

- pkg/framer/property_aggregate.go
- pkg/server/test/property_value_aggregate_test.go
I noticed that the ErrorEntries block in property_aggregates.go was inside the SuccessEntries block. I don't think it should be there because
1. This is not the case with other response processing types, [for example](https://github.com/grafana/iot-sitewise-datasource/blob/main/pkg/framer/property_value.go#L23)
2. Sitewise API reference doesn't contain anything that would suggest error entries would only be present if success entries are: https://docs.aws.amazon.com/iot-sitewise/latest/APIReference/API_BatchGetAssetPropertyAggregates.html (the response structure is the same as other BatchGetAsset* endpoints)
I moved it out so it mimics the other response processing functions.
Fixes #
**Special notes for your …
> Property aggregate processing: Move out ErrorEntries processing from SuccessEntries block

- package.json
- yarn.lock
This PR upgrades cspell, fork-ts-checker-webpack-plugin and add cosmiconfig resolution in order to upgrade the package `yaml` version. The main reason the older version of `yaml` was used was due to a transitive dependency of an older version of `cosmiconfig`.
`fork-ts-checker-webpack-plugin` and `cspell` were on older versions requiring an older version of `cosmiconfig`.
`fork-ts-checker-webpack-plugin` and `cspell` were updated, but finally `@emotion/css` still used an older version of `cosmiconfig`. So the latest version of `cosmiconfig` was added to `resolutions`. 
Fixes https://github.com/grafana/oss-plugin-partnerships/issues/465
Is the following message during `yarn …
> Upgrade yaml package

- CHANGELOG.md
- cspell.config.json
- package.json
- Update dependencies and create-plugin configuration by @idastambuk
in https://github.com/grafana/iot-sitewise-datasource/pull/243
- Property aggregate processing: Move out ErrorEntries processing from SuccessEntries block by @idastambuk
in https://github.com/grafana/iot-sitewise-datasource/pull/240
- Bump go.opentelemetry.io/contrib/instrumentation/net/http/httptrace/otelhttptrace from 0.37.0 to 0.44.0 by @dependabot
in https://github.com/grafana/iot-sitewise-datasource/pull/241
- Bump @babel/traverse from 7.17.10 to 7.23.2 by @dependabot
in https://github.com/grafana/iot-sitewise-datasource/pull/245
- Bump loader-utils from 2.0.2 to 2.0.4 by @dependabot in https://github.com/grafana/iot-sitewise-datasource/pull/248
- Bump semver from 5.7.1 to 5.7.2 by @dependabot in …
> Prepare v1.13.0

- cspell.config.json
- go.mod
- go.sum
- pkg/framer/property_interpolated.go
- pkg/models/meta.go
- pkg/models/query.go
- pkg/server/test/property_value_interpolated_test.go
- pkg/sitewise/api/property_interpolated.go
- src/DataSource.ts
- src/appendFrames.ts
- src/types.ts
It allows selecting multiple assets when using an interpolated property values query.
Before:
After:
Fixes #235 
- As a part of this another bug was fixed where when multiple assets were selected and the property values history query was selected, and the time range was long enough where a multiple queries were needed to fetch all of the data points, it would error
Before:
After:
See the screenshots for the queries used for testing. Demo assets may need to be recreated in the external dev account if it expires.
> Support multiple assets for interpolated queries

- pkg/models/asset.go
- pkg/sitewise/api/list_associated_assets.go
- src/components/query/PropertyQueryEditor.tsx
- src/types.ts
This pull request implements a flag to add an "**ALL**" option to the ListAssociatedAssets query. Listing children in this way currently isn't supported natively by the SiteWise API, so we work around this by first getting all the asset hierarchies, and requesting them individually, and unifying them at the end. This is temporary, as this API change will be added on the SiteWise end next year to improve scalability. It essentially enables the user to setup navigation through their asset hierarchies in the same way as the SiteWise Console Asset explorer does (and this uses the same approach as the console).
This is a critical feature request for one of our customers.
Fixes #
> feat: implement all option for list associated assets query

- pkg/framer/property_value.go
- pkg/server/test/property_value_test.go
We currently can't fetch the data type for disassociated data streams. This is because the describe asset property API doesn't support querying by alias, instead it requires an asset id and property id. See the following code where the `DataType` is set to `"?"`
https://github.com/grafana/iot-sitewise-datasource/blob/ef82f351fab5cd8c08c3682e348d4c834aa0f34a/pkg/resource/sitewise.go#L30-L45
Since we don't know the data type, when we're building up the frame, we were incorrectly inferring the data type to be a float64 (which is what we infer a field's value type to be by default)
https://github.com/grafana/iot-sitewise-datasource/blob/ef82f351fab5cd8c08c3682e348d4c834aa0f34a/pkg/framer/fields/util.go#L8-L19
This PR uses an existing utility function to …
> Fix: Infer data type for disassociated streams for property value queries by alias

- src/components/query/PropertyQueryEditor.tsx
**What this PR does / why we need it**: https://github.com/grafana/iot-sitewise-datasource/pull/279 included a change which caused the asset property drop-down to not render the asset property names. This is due to a reference to the wrong list, which was not caught by TypeScript, as the `options` prop of `<Select />` does not have strong type safety (i.e., it only requires a list of type `T`).
https://github.com/grafana/iot-sitewise-datasource/pull/285 acts as an effective regression test to ensure asset property list is functional.
> fix: asset property list render

- .github/workflows/e2e.yml
The `grafana/plugin-actions/publish-report` action should only run for Grafana employees. Adding an extra condition to check if the PR is not a fork before running the action.
> E2E: Publish report only when the branch is not a fork

- src/components/AggregatePicker.tsx
- src/components/query/ListAssetsQueryEditor.tsx
- src/components/query/PropertyQueryEditor.tsx
- src/components/query/QualityAndOrderRow.tsx
- src/components/query/QueryEditor.tsx
- tests/helpers.ts
- tests/interceptRequests.ts
- tests/queryEditor.model.ts
- tests/queryEditor.spec.ts
**What this PR does / why we need it**: This change includes happy path playwright query tests for all seven queries exposed by the query editor. The work includes:
- Happy path test cases for each query using mocked data and making assertions on the rendering of expected form elements.
- Addition of `QueryEditor` page object model test utility used to reduce duplication within tests and make it easier to write and maintain tests.
- Addition of `queryEditor` test fixture to remove the need to instantiate the `QueryEditor` object model explicitly in every test.
- Addition of missing ARIA labels in query editor components used for testing selectors.
Next steps:
- Tests utilizing all of the available form fields (e.g., resolution, aggregation, time, format, etc.).
- Tests for failure cases. …
> test: happy path playwright query tests

- src/components/query/ListAssetsQueryEditor.tsx
- src/components/query/PropertyQueryEditor.tsx
- src/components/query/QualityAndOrderRow.tsx
- src/components/query/QueryEditor.tsx
Sometimes when dropdowns have a lot of items, some of them are not visible because the Select prop always places the dopdown on the bottom. This changes the placement to "auto".
**Before:**
**After:**
> Query Editor: Improve menu placement for dropdowns 

- src/DataSource.test.ts
- src/DataSource.ts
- src/module.ts
- src/variables.ts
Migrates from the deprecated variable support to `CustomVariableSupport`. I created an [issue](https://github.com/grafana/iot-sitewise-datasource/issues/305) to actually design a new proper variable editor for this with resource handlers for the backend and an [issue](https://github.com/grafana/iot-sitewise-datasource/issues/306) to handle assetId and assetIds more consistently.
Fixes #233
> Migrate to CustomVariableSupport

- CHANGELOG.md
- package.json
- pkg/models/asset.go
- pkg/models/property.go
- pkg/server/test/list_asset_properties_test.go
- pkg/sitewise/api/list_asset_properties.go
- pkg/sitewise/api/list_asset_properties_test.go
Fixes listProperties to use both AssetId and AssetIds to fetch properties
Fixes #308 
> Fetch properties using both AssetId and AssetIds

- cspell.config.json
- package.json
- tests/configEditor.spec.ts
- yarn.lock
E2E tests are failing on the latest grafana-dev image. The Default Region selector wasn't able to enter `us-east-1` so there would be an error when trying to use `ap-east-1` which is an opt-in region. Not entirely sure what changed with how playwright interacts with the select element, but using the [recommended way to interact with select elements](https://grafana.com/developers/plugin-tools/e2e-test-a-plugin/selecting-elements#select-field) fixes it.
The changes to use `inputId` for `<Select>` components are in [this PR in `grafana-aws-sdk-react`](https://github.com/grafana/grafana-aws-sdk-react/pull/85)
Fixes: #317
> Fix e2e tests

- .eslintrc
Came up while reviewing https://github.com/grafana/iot-sitewise-datasource/pull/318
Not sure why this isn't on by default tbh, but seems like a good start to just add it to the individual plugin for now
> Adding a lint rule to prefer const over let

- cspell.config.json
- src/DataSource.ts
- src/RelativeRangeRequestCache/RelativeRangeCache.test.ts
- src/RelativeRangeRequestCache/RelativeRangeCache.ts
- src/RelativeRangeRequestCache/cacheIdUtils.test.ts
- src/RelativeRangeRequestCache/cacheIdUtils.ts
- src/RelativeRangeRequestCache/constants.ts
- src/RelativeRangeRequestCache/dataFrameUtils.test.ts
- src/RelativeRangeRequestCache/dataFrameUtils.ts
- src/RelativeRangeRequestCache/timeRangeUtils.test.ts
- src/RelativeRangeRequestCache/timeRangeUtils.ts
- src/RelativeRangeRequestCache/types.ts
- src/SiteWiseQueryPaginator.test.ts
- src/SiteWiseQueryPaginator.ts
- src/components/browser/AssetBrowser.tsx
- src/components/query/ClientCacheRow.tsx
- src/components/query/QueryEditor.test.tsx
- src/components/query/QueryEditor.tsx
- src/dataFrameUtils.test.ts
- src/dataFrameUtils.ts
- src/sitewiseCache.ts
- src/timeRangeUtils.test.ts
- src/timeRangeUtils.ts
- src/types.ts
- src/variables.ts
Loading a huge amount of data takes a lot of time and also, if the dashboard is set to auto refresh then most of the times the dashboard refreshes while the data is still getting loaded. This is not a good user experience and makes the dashboard unusable.
This PR added a cache to the `DataSource.ts` on the frontend. The cache `RelativeRangeCache.ts` tracks a history of the relative range requests and their data frame responses. This cache allows the DataSource to reuse the cached data frame responses and refreshes only the most recent data, reducing the request time range; hence, bringing a snappy refresh experience for customers.
**After this PR:**
- the request time was 0.3 s compares to 1.5 s before (the effect is greater for greater range)
- the …
> chore: added cache to store/refresh relative range queries.

- CHANGELOG.md
- package.json
- pkg/sitewise/datasource.go
Uses ReadAuthSettings which tries to read auth settings from context first and then automatically falls back to reading auth settings from the environment.
Also includes the changes for releasing these changes.
> Fix: use ReadAuthSettings to get authSettings

- package.json
- playwright.config.ts
- src/components/ConfigEditor.test.tsx
- src/components/ConfigEditor.tsx
- src/components/query/ClientCacheRow.tsx
- src/components/query/ListAssetsQueryEditor.tsx
- src/components/query/PropertyQueryEditor.tsx
- src/components/query/QualityAndOrderRow.tsx
- src/components/query/QueryEditor.test.tsx
- src/components/query/QueryEditor.tsx
- yarn.lock
Removes the newFormStyling feature toggle, making the new styling default. Part of https://github.com/grafana/oss-plugin-partnerships/issues/692
> Migrate to new form styling in config and query editors

- pkg/framer/fields/field_names.go
- pkg/framer/fields/fields.go
- pkg/framer/list_time_series.go
- pkg/models/asset.go
- pkg/models/query.go
- pkg/server/datasource.go
- pkg/server/handlers.go
- pkg/server/server.go
- pkg/sitewise/api/list_time_series.go
- pkg/sitewise/datasource.go
- src/RelativeRangeRequestCache/cacheIdUtils.test.ts
- src/RelativeRangeRequestCache/cacheIdUtils.ts
- src/RelativeRangeRequestCache/types.ts
- src/components/query/ListTimeSeriesQueryEditor.tsx
- src/components/query/QueryEditor.tsx
- src/queryInfo.ts
- src/types.ts
**What this PR does / why we need it**: This PR adds the implementation for the listTimeSeries API call in the SitwiseSDK. It extends the query editor with a form that allows users to populate the parameters for the API call correctly.
**Which issue(s) this PR fixes**: Users can now query disassociated data (aka unmodeled data) and filter on assetId or alias prefix for specific data streams.
Fixes #
> feat: add list time series to query editor

- pkg/sitewise/api/property_interpolated.go
- src/components/query/QualityAndOrderRow.tsx
- src/components/query/QueryEditor.test.tsx
When a "Get interpolated property values" query is used with `Quality` set to `ANY` (which is the default option) it errors because it's not a [valid value for the query](https://docs.aws.amazon.com/iot-sitewise/latest/APIReference/API_GetInterpolatedAssetPropertyValues.html#API_GetInterpolatedAssetPropertyValues_RequestSyntax). This PR removes it from the options for interpolated queries and automatically replaces `ANY` with `GOOD` on the backend (since it works on a first run and by using `GOOD` that's probably in line with users expect)
Fixes #326
> Remove ANY option for interpolated property quality

- src/components/query/QueryEditor.test.tsx
- src/components/query/QueryOptions.tsx
- src/types.ts
- tests/queryEditor.spec.ts
Removes unused fields from `Get property value` query editor
Fixes #328
> Remove unused fields from Get property value query editor

- pkg/sitewise/api/property_aggregate.go
- pkg/sitewise/api/property_aggregate_batch.go
- pkg/sitewise/api/property_history.go
- pkg/sitewise/api/property_history_batch.go
- pkg/sitewise/api/property_interpolated.go
- src/components/query/QualityAndOrderRow.tsx
- src/components/query/QueryEditor.test.tsx
We recently[ removed it for interpolated property query](https://github.com/grafana/iot-sitewise-datasource/pull/342), but we should do it for other query types too. More info https://github.com/grafana/iot-sitewise-datasource/issues/346
Fixes https://github.com/grafana/iot-sitewise-datasource/issues/346
> Remove "ANY" as a query quality option

- pkg/models/setting.go
- pkg/sitewise/auth.go
cleanup errors from running `golangci-lint run --timeout=5m`
> Fix golangci-lint errors

- pkg/framer/property_value.go
- pkg/framer/property_value_batch.go
- pkg/framer/property_value_history.go
- pkg/framer/property_value_history_batch.go
Currently, get property value and get property history error out when you query on a an asset with null or mixed value (null + value). We want to ensure make sure our experience is error free. 
Ensures that get property value and get property history to BAD or UNCERTAIN data is error free. 
https://github.com/user-attachments/assets/83e7b118-25bb-4247-b5aa-88352630357e
Fixes #
> fix: add check for nil for property value

- .github/dependabot.yml
- Groups updates according to the package ecosystem
- Sets update interval to be weekly (this will be Mondays by default)
I realized we never updated dependabot for this repo
Fixes: https://github.com/grafana/oss-plugin-partnerships/issues/927
> Chore: group dependabot updates on weekly interval

- src/components/query/PropertyQueryEditor.tsx
Currently, the user is required to input only the asset id in uuid format in order to select the asset in a query. If any user tries to enter an [external id](https://docs.aws.amazon.com/iot-sitewise/latest/userguide/object-ids.html#external-ids), the query will not be able to find timeseries data since the dataplane does not support external ids yet.
This change allows users to select assets by external ids and retrieve the timeseries data.
https://github.com/user-attachments/assets/6a5b1e78-2c18-4a98-9e7b-c5a9871a2789
In addition, a tooltip for the asset field teaches users how to enter the asset id. Users can learn more about SiteWise external ids by clicking on the API docs button.
Fixes #351
**Testing**:
- Unit …
> feat: support asset selection by external id

- CHANGELOG.md
- package.json
- (Breaking change:) Migrate to plugin-ui from grafana/experimental in [#384](https://github.com/grafana/iot-sitewise-datasource/pull/384)
- chore(deps): bump the all-go-dependencies group across 1 directory with 2 updates in [#413](https://github.com/grafana/iot-sitewise-datasource/pull/413)
- chore(deps): bump the all-node-dependencies group across 1 directory with 20 updates in [#405](https://github.com/grafana/iot-sitewise-datasource/pull/ 405)
- Bugfix: Filter out invalid queries in variable editor in [#399](https://github.com/grafana/iot-sitewise-datasource/pull/399)
- Chore: update docker compose to support improved backend development in [#397](https://github.com/grafana/iot-sitewise-datasource/pull/397)
- Bump the all-node-dependencies group with 7 updates in …
> Prepare 2.0.0

- src/variables.test.ts
- src/variables.ts
Fix isValidQuery logic to not require asset IDs for `listAssets` and `listAssetModels` queries
Before it was expecting a list of assetIDs even though [the listAssets API](https://docs.aws.amazon.com/iot-sitewise/latest/APIReference/API_ListAssets.html) and [the listAssetModels API](https://docs.aws.amazon.com/iot-sitewise/latest/APIReference/API_ListAssetModels.html) did not require it
screenshot of feature working again:
> fix: isValidQuery broken for listAssets and listAssetModels

- pkg/server/test/property_values_for_time_range_test.go
- pkg/sitewise/api/propvals/resolution_picker.go
- pkg/sitewise/api/propvals/resolution_picker_test.go
- pkg/testdata/time.go
- src/SitewiseDataSource.test.ts
- src/SitewiseDataSource.ts
- src/common/getSelectionInfo.ts
- src/common/getVariableOptions.ts
- src/components/query/AggregationSettings/AggregatePicker.tsx
- src/components/query/AggregationSettings/AggregationSettings.tsx
- src/components/query/PropertyQueryEditor.tsx
- src/types.ts
Add support for 15m resolution as well as ability to utilize resolution as a template variable.
Add's in the ability for users to utilize template variables for resolution. Makes it easier for power users to construct dynamic dashboards. Resolves a direct ask of a customer, and works towards the end goal of the plugin which is support for _all_ query parameters to support template variables
Fixes #422 
- I utilize a UX pattern established in the Grafana Twinmaker app repo in how the variables are surfaced in the inputs. The code can be seen at https://github.com/grafana/grafana-iot-twinmaker-app/blob/main/src/common/info/info.ts#L151-L180. I utilized this code with minimal …
> Feat: Add support for 15min resolution; Improve UI in dropdowns for variables and add support for variables in Resolution

- src/common/useOptionsWithVariables.ts
- src/components/query/AggregationSettings/AggregationSettings.tsx
- src/components/query/visual-query-builder/ListAssetsQueryEditor.tsx
- src/sitewiseCache.ts
Utilizes new "nested template variable" UX in dropdown for modelId on the ListAssetQuery editor.
To help improve UX, and UX consistency.
N/A
Fixes #
- Reactivity bug
There is a minor reactivity bug for template variable values to flow down to the dropdown, where if a user changes the variables, it isn't immediately reflected in a dropdown.
This is a reactivity bug that is present already, a bit of a niche case that should be resolved but I think will require a larger refactor of dataflow to turn template variables to be passed in higher in the component tree that I want to tackle seperately.
- Cache refactor
I want to work towards uncoupling the caching module from options. To …
> feat: Support nested variable UX for modelId

- src/SitewiseDataSource.test.ts
- src/SitewiseDataSource.ts
- src/SitewiseQueryEditor.tsx
- src/components/ConfigEditor.tsx
- src/components/browser/AssetBrowser.tsx
- src/components/query/visual-query-builder/PropertyQueryEditor.tsx
- src/components/query/visual-query-builder/VisualQueryBuilder.test.tsx
- src/components/query/visual-query-builder/VisualQueryBuilder.tsx
- src/regions.ts
- src/sitewiseCache.ts
- src/types.ts
The datasource currently allows the user to select a large number of regions which do not support the AWS IoT SiteWise service.
Attempting to run a query in a region not supported by IoT SiteWise, such as the first region listed in the region drop-down, ap-east-1, leads to the following error:
```sh
failed to fetch query data: RequestError: send request failed caused by: Get "https://api.iotsitewise.ap-east-1.amazonaws.com/asset-models?maxResults=250": dial tcp: lookup api.iotsitewise.ap-east-1.amazonaws.com on 10.0.0.2:53: no such host
```
This PR removes the unsupported regions from the drop-down.
Additionally, as an improvement, the change enforces region type-safety via the `Region` type, a union of the string literal region names.
> fix: remove unsupported regions

- src/README.md
- src/SitewiseQueryEditor.tsx
- src/components/query/visual-query-builder/ClientCacheRow.tsx
- src/components/query/visual-query-builder/VisualQueryBuilder.tsx
- tests/queryEditor.spec.ts
1. SiteWise service team determined that the Code editor feature is not yet ready for release. Code editor queries result in an error when there are multiple queries sent. This PR disables Code editor feature and no users will be able to utilize it.
1. Queries with client cache enabled do not account for variable changes in properties and variable query result will not update when client cache is enabled. This PR makes client cache disabled by default.
Fixes #
SiteWise service team is prioritizing the issue aforementioned.
> fix: disabled code editor and client cache to prepare for release

- src/components/query/visual-query-builder/ClientCacheRow.tsx
- src/components/query/visual-query-builder/VisualQueryBuilder.tsx
This PR removed the `id` attribute from `<Switch>` of client cache to avoid only the first `<Switch>`'s `onChange` is triggered. This fixes the issue #450  
Fixes #450
> fix: client cache switch should control the correct query

- src/RelativeRangeRequestCache/cacheIdUtils.test.ts
- src/RelativeRangeRequestCache/cacheIdUtils.ts
- src/SitewiseDataSource.ts
- src/components/query/visual-query-builder/ClientCacheRow.tsx
- src/components/query/visual-query-builder/VisualQueryBuilder.tsx
This PR fixes issue #417 - When client cache is enabled, changes in variable is not detected by client cache. Changes is not detected because the variable is a placeholder (e.g. `${asset}`) and not the actual value before passing to the client cache. Hence, changes in the variable value does not change the placeholder and client cache considers no changes in the query.
Changes includes:
- `SitewiseDataSource` to interpolate variables before cache retrieval/storage (so the query properties are replaced by actual variable-values and not just variable-names)
- update client cache key to respect new SiteWiseQuery properties `propertyIds` and `propertyAliases` 
After the fix, the variable is respected: …
> fix: client cache should respect variable changes

- src/README.md
- src/plugin.json
We have incidents that customers using Grafana instances with versions prior to v10 are unable to see plugin versions beyond 1.25.2. To resolve this, we recommend that these customers upgrade their Grafana instances to version 10 or higher. This will ensure they can access the latest plugin versions and functionality.
To notify customers about the need to upgrade, we suggest adding a prominent message on the plugin page informing users that versions beyond 1.25.2 require a Grafana instance of v10 or later. This will help raise awareness and guide customers to the necessary upgrade to continue benefiting from the Grafana SiteWise plugin.
Render of the readme with the warning message.
Fixes #
**Special notes for your …
> chore: grafana instance version support warnning

- .github/workflows/detect-breaking-changes.yml
- .github/workflows/e2e.yml
- .github/workflows/issue-commands.yml
- .github/workflows/pr-commands.yml
- .github/zizmor.yml
- cspell.config.json
As per Zizmor warnings. I also changed uses: nev7n/wait_for_response@v1 for "wait for grafana" step to the grafana action to follow what we have in other repos. if this cause e2e tests to fail, we can add the config back and see if that helps
> Chore: Update github workflows and add zizmor

- .github/workflows/publish.yaml
- .github/workflows/push.yaml
- .golangci.yml
- .prettierrc.js
- eslint.config.mjs
- package.json
- pkg/models/model.go
- pkg/models/setting.go
- pkg/resource/caching_resource_provider.go
- pkg/server/last-observation.go
- pkg/sitewise/api/list_associated_assets.go
- pkg/sitewise/api/test_data_test.go
- pkg/sitewise/auth.go
- pkg/sitewise/datasource.go
- src/RelativeRangeRequestCache/cacheIdUtils.ts
- src/SiteWiseQueryPaginator.test.ts
- src/SitewiseDataSource.ts
- src/SitewiseQueryEditor.tsx
- src/common/useOptionsWithVariables.ts
- src/components/query/visual-query-builder/ListTimeSeriesQueryEditor.tsx
- src/components/query/visual-query-builder/PropertyQueryEditor.tsx
- src/components/query/visual-query-builder/QualityAndOrderRow.tsx
- src/components/query/visual-query-builder/VisualQueryBuilder.test.tsx
- src/components/query/visual-query-builder/VisualQueryBuilder.tsx
- src/migrations/migrateQuery.ts
- src/queryInfo.ts
- src/regions.ts
- src/sitewiseCache.ts
- yarn.lock
This migrates the plugin CI/CD processes to Github actions according to [this migration guide](https://enghub.grafana-ops.net/docs/default/component/grafana-plugins-platform/plugins-ci-github-actions/020-migrating-form-drone/)
Right now the shared workflows don't have a mechanism to specify custom Vault secrets in e2e tests, so I had to disable the shared e2e workflow and keep our old e2e action. This might change in the future, but with drone sunset coming up, we don't really have a choice. More info [in this thread ](https://raintank-corp.slack.com/archives/C01C4K8DETW/p1750077883269419?thread_ts=1750072014.548489&cid=C01C4K8DETW)
+ Also had to migrate to eslintv9 so there were a lot of eslint errors and warnings
+ golangci-lint errors
+ had to change resource calls in sitewiseCache to …
> Chore: Migrate to Github actions + migrate to eslintv9

- .github/dependabot.yml
- .github/workflows/dependabot-reviewer.yml
- .github/workflows/e2e.yml
- cspell.config.json
- package.json
- yarn.lock
Changes:
- Adds support for the cooldown feature for the github-actions, go and npm ecosystems in `.github/dependabot.yml`. https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#cooldown-
- Uses the existing workflow to automerge dependabot updates https://github.com/grafana/security-github-actions/blob/main/.github/workflows/dependabot-automerge.yaml
- Downgraded the version of react-router-dom to v6 since we don't actually support v7 yet. We aren't actually using anything specific in react-router-dom so this should be fine since Grafana is actually still on v5.
- I removed the resolutions for dependencies that were added for CVEs or for fixing tests. Running `yarn why` on each of the dependencies listed in the resolutions list showed …
> Add support for auto-merging dependabot updates

- CHANGELOG.md
- package.json
- pkg/server/server.go
ErrorBudgetBurnRateTooHigh warnings in operation channel. These errors should be downstream errors, not plugin errors
https://raintank-corp.slack.com/archives/C077F654GCS/p1753890062885989
N/A
Fixes #
> add downstream error source in failed reques

- CHANGELOG.md
- package.json
- pkg/main.go
- pkg/server/handlers.go
- pkg/server/handlers_test.go
- pkg/server/test/server_test.go
- pkg/sitewise/datasource.go
- src/components/query/visual-query-builder/VisualQueryBuilder.test.tsx
- src/components/query/visual-query-builder/VisualQueryBuilder.tsx
- src/regions.ts
Fixes https://github.com/grafana/iot-sitewise-datasource/issues/551
Also set isClearable to false, since it shouldn't be possible for users to clear the region, since Default is one of the options
> QueryData: Set default region if empty, prepare 2.3.2
